%PDF-1.4
%Çì¢
5 0 obj
<</Length 6 0 R/Filter /FlateDecode>>
stream
xœ•VMoÓ@½ûWŒ¸P^ï·×å‚€HrGn²qLã¤õ‡JùõÌú³Nj;('ñì{oŞÎÌîPÂ€ºOû\g^ğ#„¤ğ($ŞƒÇê—Ğ>Ö|\a€I¬¶^³ˆ0„re äŒhXeŞ{³ú‘4q‚!%Æ®6ŞUç‰-ƒ½­’à6-ã|c×Päëà-É‹fiOâw«}S/ç#hÅH8@¯ú·Uºßœ¢t-ŠhŞcf/(ÌíŞÆ…ñ¨Pó6bZ­¤$bTu<ò2µàû#ÒIİj¯<Vë´8¤üS.`éÖöâ.Ù¢obD–³œ¨gáböc	Ü Î)ÿ€nèİ,zá@.0"rï}æÒ¦û“Ñ“‘Dkv%rŸİQ„1Îâ	z’q£(A¨6æ‚jn;¾ƒ‚/ƒ3PûHĞöo[g×¸Á›o?ƒ·.ëÎ›i’º-ğûWü®Ş¼´‡ÄØfI8æÌf8ó+)âº'Ô‹õTÓªër¾bfFp¼ß˜œûİ	vÛğDi90E3r?ØõîY|—’/>l&Üß%YÈÏVõú˜eé¸íÑH){ÃÏ¦À²×ú\9'i	ø1øÙ«V	orgGkbU³¸´›.]…õ.>$¶€Ç´ÜÁ>şû™-Š8±'}hú1õê½£¼¯Šİyrbtß…œÏ™R”qYcSÜvQ>å
‡œ›~®¥œÄçÓ;'çDnÒívl'RD“‡Ç£¦ï®$:ü³&;U¨gkÇÅaì"%R©¡7ÎlÄ™Êå 1\ìágÓ*ÍL¿íÙ³ôu®cÔ`¸ø¤ñÇ–ëÙ…qúÇè_Z^4SEİÙŸVŞw4–Â£‡qÁK
¡ˆ4d2¡Â©í½Ÿ^è"»*-\€ÃÈ-Lß±sŸ_5‚J"T}üŒ¹1ıŞ\Óz,ÈˆiTëÉv.°€õ%ÃT;	ñB;ç¾Åwv›îíÊšv*C†´ÿ%SjE"…+UsS½ÉÓƒ›4·OíM¬*l÷i}%’ÕÁ~(=«Ê›ø	0½¼Šó'ÌïZÕÌk%C"º¡Ğ¦V‹şîı\ı±%endstream
endobj
6 0 obj
854
endobj
4 0 obj
<</Type/Page/MediaBox [0 0 612 792]
/Rotate 0/Parent 3 0 R
/Resources<</ProcSet[/PDF /Text]
/ExtGState 13 0 R
/Font 14 0 R
>>
/Contents 5 0 R
>>
endobj
3 0 obj
<< /Type /Pages /Kids [
4 0 R
] /Count 1
>>
endobj
1 0 obj
<</Type /Catalog /Pages 3 0 R
/Metadata 16 0 R
>>
endobj
7 0 obj
<</Type/ExtGState
/OPM 1>>endobj
13 0 obj
<</R7
7 0 R>>
endobj
14 0 obj
<</R8
8 0 R/R9
9 0 R/R10
10 0 R/R11
11 0 R/R12
12 0 R>>
endobj
8 0 obj
<</BaseFont/Helvetica/Type/Font
/Subtype/Type1>>
endobj
9 0 obj
<</BaseFont/Courier/Type/Font
/Encoding 15 0 R/Subtype/Type1>>
endobj
15 0 obj
<</Type/Encoding/Differences[
45/minus]>>
endobj
10 0 obj
<</BaseFont/Helvetica-Bold/Type/Font
/Subtype/Type1>>
endobj
11 0 obj
<</BaseFont/Courier-Bold/Type/Font
/Subtype/Type1>>
endobj
12 0 obj
<</BaseFont/Times-Roman/Type/Font
/Subtype/Type1>>
endobj
16 0 obj
<</Type/Metadata
/Subtype/XML/Length 1344>>stream
<?xpacket begin='ï»¿' id='W5M0MpCehiHzreSzNTczkc9d'?>
<?adobe-xap-filters esc="CRLF"?>
<x:xmpmeta xmlns:x='adobe:ns:meta/' x:xmptk='XMP toolkit 2.9.1-13, framework 1.6'>
<rdf:RDF xmlns:rdf='http://www.w3.org/1999/02/22-rdf-syntax-ns#' xmlns:iX='http://ns.adobe.com/iX/1.0/'>
<rdf:Description rdf:about='uuid:2c903599-6c64-11f4-0000-8d8e4ba2bb5d' xmlns:pdf='http://ns.adobe.com/pdf/1.3/' pdf:Producer='GPL Ghostscript 9.07'/>
<rdf:Description rdf:about='uuid:2c903599-6c64-11f4-0000-8d8e4ba2bb5d' xmlns:xmp='http://ns.adobe.com/xap/1.0/'><xmp:ModifyDate>2019-02-19T08:09:44-05:00</xmp:ModifyDate>
<xmp:CreateDate>2019-02-19T08:09:44-05:00</xmp:CreateDate>
<xmp:CreatorTool>UnknownApplication</xmp:CreatorTool></rdf:Description>
<rdf:Description rdf:about='uuid:2c903599-6c64-11f4-0000-8d8e4ba2bb5d' xmlns:xapMM='http://ns.adobe.com/xap/1.0/mm/' xapMM:DocumentID='uuid:2c903599-6c64-11f4-0000-8d8e4ba2bb5d'/>
<rdf:Description rdf:about='uuid:2c903599-6c64-11f4-0000-8d8e4ba2bb5d' xmlns:dc='http://purl.org/dc/elements/1.1/' dc:format='application/pdf'><dc:title><rdf:Alt><rdf:li xml:lang='x-default'>Untitled</rdf:li></rdf:Alt></dc:title></rdf:Description>
</rdf:RDF>
</x:xmpmeta>
                                                                        
                                                                        
<?xpacket end='w'?>
endstream
endobj
2 0 obj
<</Producer(GPL Ghostscript 9.07)
/CreationDate(D:20190219080944-05'00')
/ModDate(D:20190219080944-05'00')>>endobj
xref
0 17
0000000000 65535 f 
0000001177 00000 n 
0000003211 00000 n 
0000001118 00000 n 
0000000958 00000 n 
0000000015 00000 n 
0000000939 00000 n 
0000001242 00000 n 
0000001385 00000 n 
0000001449 00000 n 
0000001585 00000 n 
0000001655 00000 n 
0000001723 00000 n 
0000001283 00000 n 
0000001313 00000 n 
0000001527 00000 n 
0000001790 00000 n 
trailer
<< /Size 17 /Root 1 0 R /Info 2 0 R
/ID [<E62D092BBE7E885A7C2D38FD2D5FCDA3><E62D092BBE7E885A7C2D38FD2D5FCDA3>]
>>
startxref
3334
%%EOF
