.TH "BITWARDEN REGISTER" "1" "24-Jan-2019" "" "bitwarden register Manual"
.SH NAME
bitwarden\-register \- register a new account on server.
.SH SYNOPSIS
.B bitwarden register
[OPTIONS] EMAIL
.SH DESCRIPTION
register a new account on server.
.SH OPTIONS
.TP
\fB\-\-password\fP TEXT
.PP
.TP
\fB\-\-hint\fP TEXT
.PP
.TP
\fB\-\-name\fP TEXT
.PP