.TH "BITWARDEN EMTPYDB" "1" "24-Jan-2019" "" "bitwarden emtpydb Manual"
.SH NAME
bitwarden\-emtpydb \- Flush and empty the database of all values.
.SH SYNOPSIS
.B bitwarden emtpydb
[OPTIONS]
.SH DESCRIPTION
Flush and empty the database of all values.
.PP
***THIS ERASES DATA***
.PP
This gives you a nice clean fresh feeling, and erases all values
including any configuration and settings.
so be *CAREFUL* and be *SURE* you want to do this, before
doing so.
.PP
***THIS ERASES DATA***
.SH OPTIONS
.TP
\fB\-\-yes\fP
Confirm the action without prompting.